### ISSUE TITLE
Serving or building ElectronJS application gives error

### ISSUE THREAD

**Issue by Distrect** [bennymeg/nx-electron#311]
**Error Descripton**
When i run the build or serve script, it is throws "Cannot read properties of undefined (reading 'projects')" error

**To Reproduce**
1. Create nx workspace ` npx create-nx-workspace --preset=apps`
2. Install nx-electron `nx add nx-electron`
3. Create electron app by `nx g nx-electron:app` app name:project-tool,directory:<empty>,web app name:client
4. Serve or build electron app by `nx project-tool:serve`

**Error Output**
`TypeError: Cannot read properties of undefined (reading 'projects')
    at getSourceRoot (C:\Users\myfor\OneDrive\Masaüstü\projectTool\node_modules\nx-electron\src\utils\workspace.js:5:52)
    at executor (C:\Users\myfor\OneDrive\Masaüstü\projectTool\node_modules\nx-electron\src\executors\build\executor.js:17:71)
    at runExecutorInternal (C:\Users\myfor\OneDrive\Masaüstü\projectTool\node_modules\nx\src\command-line\run\run.js:98:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async C:\Users\myfor\OneDrive\Masaüstü\projectTool\node_modules\nx\src\command-line\run\run.js:176:44
    at async handleErrors (C:\Users\myfor\OneDrive\Masaüstü\projectTool\node_modules\nx\src\utils\handle-errors.js:8:24)
    at async process.<anonymous> (C:\Users\myfor\OneDrive\Masaüstü\projectTool\node_modules\nx\bin\run-executor.js:59:28)`

**Expected behavior**
I am expecting to application run and build without error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2 22631.4317
 - nx-electron version: ^19.0.0

**Comment by AntoineRosse1400** [comment]
Same issue for me.

**Comment by glani** [comment]
incompatible with nx 20. we need changes from https://github.com/bennymeg/nx-electron/pull/315

**Comment by faribauc** [comment]
Update `nx-electron` to the latest beta
```
    "nx-electron": "^20.0.0-alpha.0",
```
